name: ziggeo_example
description: Demonstrates how to use the ziggeo plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  There is a bug in 8.0.5
#  https://githubmemory.com/repo/ponnamkarthik/FlutterToast/issues/300
  fluttertoast: 8.0.4
  flutter_html: ^1.3.0
  url_launcher: ^6.0.3
  flutter_email_sender: ^5.0.0
  intl: ^0.17.0-nullsafety.2
  provider: ^4.3.1
  flutter_speed_dial: ^1.2.5
  loading_overlay: ^0.3.0
  shared_preferences: ^2.0.5
  firebase_core: "^1.0.4"
  firebase_crashlytics: "^2.0.1"

  ziggeo:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/locale/
    - assets/img/
    - assets/img/clients/
    - assets/img/sdks/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand_regular.ttf
        - asset: assets/fonts/quicksand_bold.ttf
          weight: 700
