name: ziggeo_example
description: Demonstrates how to use the ziggeo plugin.

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  ziggeo:
    path: ../

flutter:
  uses-material-design: true
