name: ziggeo_example
description: Demonstrates how to use the ziggeo plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: 8.0.9
  url_launcher: ^6.0.12
  flutter_html: ^2.2.1
  flutter_email_sender: ^5.1.0
  intl: ^0.17.0
  provider: ^6.0.1
  flutter_speed_dial: ^4.4.0+2
  loading_overlay: ^0.3.0
  shared_preferences: ^2.0.15
  firebase_core: ^1.19.1
  firebase_crashlytics: ^2.8.4

  ziggeo:
    path: ../

dev_dependencies:
  test: '^1.21.1'
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/locale/
    - assets/img/
    - assets/img/clients/
    - assets/img/sdks/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand_regular.ttf
        - asset: assets/fonts/quicksand_bold.ttf
          weight: 700
