name: ziggeo_example
description: Demonstrates how to use the ziggeo plugin.

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fluttertoast: ^7.0.1
  cupertino_icons: ^0.1.3
  flutter_html: ^1.0.0
  url_launcher: ^5.5.0
  flutter_email_sender: ^3.0.1
  intl: ^0.16.1
  provider: ^4.3.1
  flutter_speed_dial: ^1.2.5
  loading_overlay: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^0.5.8
  ziggeo:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/locale/
    - assets/img/
    - assets/img/clients/
    - assets/img/sdks/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand_regular.ttf
        - asset: assets/fonts/quicksand_bold.ttf
          weight: 700
