name: ziggeo_example
description: Demonstrates how to use the ziggeo plugin.

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fluttertoast: ^4.0.1
  cupertino_icons: ^0.1.3
  flutter_html: ^1.0.0
  url_launcher: ^5.4.10
  flutter_email_sender: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  ziggeo:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/locale/
    - assets/img/clients/
    - assets/img/sdks/
