name: ziggeo
description: A Flutter plugin for getting access to Ziggeo services and ability to easely implement camera related functionality. Supports previewing the camera feed, capturing video, screen recording, etc.
version: 0.0.1
author: Ziggeo
homepage: https://github.com/Ziggeo/Flutter-SDK

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ziggeo.flutterplugin
    pluginClass: ZiggeoPlugin
