name: ziggeo
description: A Flutter plugin for getting access to Ziggeo services and ability to easely implement camera related functionality. Supports previewing the camera feed, capturing video, screen recording, etc.
version: 0.1.5
homepage: https://github.com/Ziggeo/Flutter-SDK

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ziggeo.flutterplugin
        pluginClass: ZiggeoPlugin
