name: Ziggeo Release build
on:
  push:
    branches: [ 'feature_build_cicd' ]

jobs:
  drive_android:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'
          channel: 'stable'
      - name: "Check Flutter Release Version"
        run: |
          flutter pub publish --dry-run

      - name: "Run Flutter Release Publish"
        run: |
          flutter pub publish -f

